$HOME/.config/waybar/config.jsonc
{
    "layer": "top", // Waybar at top layer
    "position": "top", // Waybar position (top|bottom|left|right)
    "height": 51, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    "spacing": 2, // Gaps between modules (4px)
    // Choose the order of the modules
    // "margin-left":25,
    // "margin-right":25,
    "margin-bottom":-13,
    "margin-top":-5,
    "modules-left": ["hyprland/workspaces","custom/cycle_wall"],
    "modules-right": ["cpu","memory","network","pulseaudio" ,"backlight", "battery","tray"],
    "modules-center": [ "clock"],
    // Modules configuration


    // custom modules //
    "custom/cycle_wall":{
        "format":"  󰊠  ",
        // "interval": 1,
        "on-click": "$HOME/.local/bin/cycle_wall.sh",
        "tooltip": false

    },

    "custom/audio_idle_inhibitor": {
		"format": "{icon}",
		"exec": "sway-audio-idle-inhibit --dry-print-both-waybar",
		"exec-if": "which sway-audio-idle-inhibit",
        "on-click": "playerctl stop",
		"return-type": "json",
        "tooltip": false,
		"format-icons": {
			"output": "󰝚",
			"input": "󰍬",
			"output-input": "󰐌 󰍬",
			"none": ""
		}
	},
    "custom/weather": {
        "exec": "python $HOME/.local/bin/scripts/weather.py",
        "restart-interval": 300,
        "return-type": "json",
        "on-click": "xdg-open https://weather.com/en-IN/weather/today/l/$(location_id)"
        // "format-alt": "{alt}",
    },

    // End of custom modules //
"hyprland/workspaces": {
  "format": "{icon}",
  "on-click": "activate",
  "all-outputs": true,
  "sort-by-number": true,
  "format-icons": {
    "1": " ",
    "2": " ",
    "3": " ",
    "4": " ",
    "5": " ",
    "6": " ",
    "7": " ",
    "8": "󰇮 ",
    "9": "󰓇 ",
    "10": " ",
    "urgent": " ",
    "default": " "
 },
  "window-rewrite-default": " ",
  "window-rewrite": {
    "title<.*youtube.*>": " ",
    "class<firefox>": " ",
    "class<firefox> title<.*github.*>": " ",
    "foot": " ",
    "code": "󰨞 ",
    "kitty": " ",
    "Chromium": " "
  },
  "on-scroll-up": "hyprctl dispatch workspace e+1",
  "on-scroll-down": "hyprctl dispatch workspace e-1"
},
    "tray": {
        "icon-size": 18,
        "spacing": 8,
        "show-passive-items": false
    },
    "clock": {
        // "timezone": "America/New_York",
        "timezone": "America/Buenos_Aires",
        "tooltip": false,
        "interval": 60,
        "format": "{:%H:%M}",
        "max-length": 25,
        "on-click": "kitty  --class calendar -e calcure"
    },
    "cpu": {
        "interval":1,
        "format": "{icon0} {icon1} {icon2} {icon3}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"],
        "on-click": "kitty --class system_monitor -e htop"

    },
    "memory": {
        "format": "{percentage}% 󰇖",
        "interval": 1,
        "on-click": "kitty --class system_monitor -e htop",
        "max-lenght": 35
    },
    "backlight": {
        // "device": "acpi_video1",
        "format": "{percent}% {icon}",
        "on-scroll-down": "swayosd-client --brightness raise",
        "on-scroll-up": "swayosd-client --brightness lower",
        "format-icons": ["󰃚", "󰃚", "󰃛", "󰃜", "󰃜", "󰃝", "󰃞", "󰃟", "󰃠"]
    },
    "battery": {
        "states": {
            "warning": 50,
            "critical": 20
        },
        "format": "{capacity}% {icon}",
        "format-charging": "{capacity}% 󰂅",
        "format-plugged": "{capacity}% {icon}",
         "format-good": "", // An empty format will hide the module
         "format-full": "󰁹",
        "format-icons": ["󰂎","󰁺","󰁻","󰁼","󰁽","󰁾","󰁿", "󰂀", "󰂁", "󰂂", "󰁹"],
        "on-click": "$HOME/.config/rofi/powermenu/type-5/powermenu.sh",
    },
    "pulseaudio": {
        "format": "{volume}% {icon}",
        "format-bluetooth": "{volume}% {icon}",
        "format-bluetooth-muted": "婢  muted",
        "format-muted": "󰖁 muted",
        "format-icons": {
            "headphone": "󰋋",
            "hands-free": "",
            "headset": "󰋋",
            "phone": "󰄜",
            "portable": "",
            "car": "󰸛",
            "default": ["󰕿", "󰖀", "󰕾"]
        },
        "on-click-right": "pavucontrol",
      "on-click": "swayosd-client --output-volume mute-toggle",
      "on-scroll-down": "swayosd-client --output-volume raise",
      "on-scroll-up": "swayosd-client --output-volume lower",
    },
    "network": {
         "interface": "wlan0",
        "format-wifi":  " {signalStrength}% 󰤨 ",
        "format-disconnected": " Offline 󰤭 ",
        "tooltip-format": "{ifname} via {gwaddr} 󰱶",
        "tooltip-format-wifi": "{essid}",
        //"on-click": "$HOME/.local/bin/scripts/rofi-wifi-menu"
    }
}

