$HOME/.config/waybar/config.jsonc
{
    "layer": "top", // Waybar at top layer
    "position": "top", // Waybar position (top|bottom|left|right)
    "height": 52, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    "spacing": 2, // Gaps between modules (4px)
    // Choose the order of the modules
    "margin-left":-10,
    "margin-right":-10,
    "margin-bottom":-5,
    "margin-top":-5,
    "modules-left": ["hyprland/workspaces", "custom/cycle_wall"],
    "modules-right": ["tray", "cpu", "memory", "pulseaudio" , "battery", "custom/updates", "clock"],
    "modules-center": ["hyprland/window"],
    // Modules configuration


"hyprland/workspaces": {
  "format": "{icon}",
  "on-click": "activate",
  "all-outputs": true,
  "sort-by-number": true,
  "format-icons": {
    "1": " ",
    "2": " ",
    "3": " ",
    "4": " ",
    "5": " ",
    "6": " ",
    "7": " ",
    "8": "󰇮 ",
    "9": "󰓇 ",
    "10": " ",
    "urgent": " ",
    "default": " "
 },
  "window-rewrite-default": " ",
  "window-rewrite": {
    "title<.*youtube.*>": " ",
    "class<firefox>": " ",
    "class<firefox> title<.*github.*>": " ",
    "foot": " ",
    "code": "󰨞 ",
    "kitty": " ",
    "Chromium": " "
  },
  "on-scroll-up": "hyprctl dispatch workspace e+1",
  "on-scroll-down": "hyprctl dispatch workspace e-1"
},

    "hyprland/window": {
        "max-length": 30,
        "separate-outputs": true
     },
    
    "hyprland/submap": {
        "format": "✌️ {}",
        "max-length": 8,
        "tooltip": false
    },

    // custom modules //
    "custom/cycle_wall":{
        "format":"  󰊠  ",
        // "interval": 1,
        "on-click": "sleep 0.1;$HOME/.local/bin/cycle_wall.sh",
        "tooltip": false
    },

    "custom/waybar-mpris": {
        "return-type": "json",
        "max-length": 40,
        "exec": "waybar-mpris --position --autofocus --pause 󰏤 --play 󰐊",
        "on-click": "sleep 0.1; waybar-mpris --send toggle",
        // This option will switch between players on right click.
            "on-click-right": "sleep 0.1; playerctl next",
        // The options below will switch the selected player on scroll
            // "on-scroll-up": "waybar-mpris --send player-next",
            // "on-scroll-down": "waybar-mpris --send player-prev",
        // The options below will go to next/previous track on scroll
            // "on-scroll-up": "waybar-mpris --send next",
            // "on-scroll-down": "waybar-mpris --send prev",
        "escape": true
    },

    "jack": {
        "format": "DSP {}%",
        "format-xrun": "{xruns} xruns",
        "format-disconnected": "DSP off",
        "realtime": true
    },

    "custom/audio_idle_inhibitor": {
		"format": "{icon}",
		"exec": "sway-audio-idle-inhibit --dry-print-both-waybar",
		"exec-if": "which sway-audio-idle-inhibit",
		"return-type": "json",
		"format-icons": {
			"output": "󰐌",
			"input": "",
			"output-input": "  ",
			"none": ""
		}
	},

    "tray": {
        "icon-size": 14,
        "spacing": 8,
        "show-passive-items": false
    },
    "clock": {
        // "timezone": "America/New_York",
        "timezone": "America/Buenos_Aires",
        "tooltip": false,
        "interval": 60,
        "format": "{:%H:%M}",
        "max-length": 25,
        "on-click": "sleep 0.1; ~/.config/hypr/scripts/wall"
    },
    "cpu": {
        "interval":1,
        "format": "{icon0} {icon1} {icon2} {icon3}",
        "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"],
        "on-click": "sleep 0.1; foot  htop"

    },
    "memory": {
        "format": "{percentage}% 󰇖",
        "interval": 1,
        "on-click": "sleep 0.1; foot --class system_monitor -e htop",
        "max-lenght": 35
    },
    "backlight": {
        // "device": "acpi_video1",
        "format": "{percent} {icon}",
        "on-scroll-down": "sleep 0.1; ~/.config/hypr/scripts/brightness --inc",
        "on-scroll-up": "sleep 0.1; ~/.config/hypr/scripts/brightness --dec",
        "format-icons": ["󰃚", "󰃚", "󰃛", "󰃜", "󰃜", "󰃝", "󰃞", "󰃟", "󰃠"]
    },
    "battery": {
        "states": {
            "warning": 50,
            "critical": 20
        },
        "format": "{capacity} {icon}",
        "format-charging": "{capacity} 󰂅",
        "format-plugged": "{capacity} {icon}",
         "format-good": "", // An empty format will hide the module
         "format-full": "󰁹",
        "format-icons": ["󰂎","󰁺","󰁻","󰁼","󰁽","󰁾","󰁿", "󰂀", "󰂁", "󰂂", "󰁹"],
        "on-click": "sleep 0.1; ~/.config/hypr/scripts/wofi-power.sh"
    },
    "pulseaudio": {
        "format": "{volume} {icon}",
        "format-bluetooth": "{volume} {icon}",
        "format-bluetooth-muted": "off 󰋋",
        "format-muted": "󰝟",
        "format-icons": {
            "headphone": "󰋋",
            "hands-free": "",
            "headset": "󰋋",
            "phone": "󰄜",
            "portable": "",
            "car": "󰸛",
            "default": ["󰕿", "󰖀", "󰕾"]
        },
        "on-click-right": "sleep 0.1 && pavucontrol",
      "on-click": "sleep 0.1 && ~/.local/bin/scripts/volume --toggle",
      "on-scroll-down": "sleep 0.1 && ~/.local/bin/scripts/volume --inc",
      "on-scroll-up": "sleep 0.1 && ~/.local/bin/scripts/volume --dec"
    },
    "network": {
        "interface": "wlp2s0",
        "on-click": "sleep 0.1 && wofi-wifi-menu",
        "format": "{ifname}",
        "format-wifi": "{essid} ({signalStrength}%) ",
        "format-ethernet": "{ifname} ",
        "format-disconnected": "", //An empty format will hide the module.
        "format-disconnected": "",
        "tooltip-format": "{ifname}",
        "tooltip-format-wifi": "{essid} ({signalStrength}%) ",
        "tooltip-format-ethernet": "{ifname} ",
        "tooltip-format-disconnected": "Disconnected",
        "max-length": 50
    },
    "custom/notification": {
        "tooltip": false,
        "format": "{icon}",
        "format-icons": {
          "notification": "󱅫",
          "none": "󰂚",
          "dnd-notification": "󰂛",
          "dnd-none": "󰂛",
          "inhibited-notification": "󰂞",
          "inhibited-none": "󰂛",
          "dnd-inhibited-notification": "󰂞",
          "dnd-inhibited-none": ""
        },
        "return-type": "json",
        "exec-if": "which swaync-client",
        "exec": "swaync-client -swb",
        "on-click": "sleep 0.1s && swaync-client -t -sw",
      //  "on-click-right": "sleep 0.1 && swaync-client -d -sw",
        "escape": true
      }
},

"custom/updates": {
    "format": "{} {icon}",
    "return-type": "json",
    "format-icons": {
        "has-updates": "󱍷",
        "updated": "󰂪"
    },
    "exec-if": "which waybar-module-pacman-updates",
    "exec": "waybar-module-pacman-updates"
}

