$HOME/.config/waybar/style.css
* {
    border: none;
    border-radius: 0px;
    font-family: "JetBrainsMono Nerd Font";
    font-weight: bold;
    font-size: 10px;
    min-height: 10px;
}

@import "theme.css";

window#waybar {
    background: @bar-bg;
}

tooltip {
    background: @main-bg;
    color: @main-fg;
    border-radius: 7px;
    border-width: 0px;
}

#workspaces button {
    box-shadow: none;
	text-shadow: none;
    padding: 0px;
    border-radius: 9px;
    margin-top: 3px;
    margin-bottom: 3px;
    margin-left: 0px;
    padding-left: 3px;
    padding-right: 3px;
    margin-right: 0px;
    color: @main-fg;
    animation: ws_normal 20s ease-in-out 1;
}

#workspaces button.active {
    background: #ebbcba;
    color: @wb-act-fg;
    margin-left: 3px;
    padding-left: 12px;
    padding-right: 12px;
    margin-right: 3px;
    animation: ws_active 20s ease-in-out 1;
    transition: all 0.4s cubic-bezier(.55,-0.68,.48,1.682);
    opacity: 0.90;
}

#workspaces button:hover {
    background: @wb-hvr-bg;
    color: @wb-hvr-fg;
    animation: ws_hover 20s ease-in-out 1;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#taskbar button {
    box-shadow: none;
	text-shadow: none;
    padding: 0px;
    border-radius: 9px;
    margin-top: 3px;
    margin-bottom: 3px;
    margin-left: 0px;
    padding-left: 3px;
    padding-right: 3px;
    margin-right: 0px;
    color: @wb-color;
    animation: tb_normal 20s ease-in-out 1;
}

#taskbar button.active {
    background: #ebbcba;
    color: @wb-act-color;
    margin-left: 3px;
    padding-left: 12px;
    padding-right: 12px;
    margin-right: 3px;
    animation: tb_active 20s ease-in-out 1;
    transition: all 0.4s cubic-bezier(.55,-0.68,.48,1.682);
    opacity: 0.90;
}

#taskbar button:hover {
    background: @wb-hvr-bg;
    color: @wb-hvr-color;
    animation: tb_hover 20s ease-in-out 1;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#tray menu * {
    min-height: 16px
}

#tray menu separator {
    min-height: 10px
}

#backlight,
#battery,
#bluetooth,
#clock,
#custom-cpuinfo,
#cpu,
#custom-gpuinfo,
#idle_inhibitor,
#custom-keybindhint,
#language,
#memory,
#custom-wallchange,
#custom-theme,
#custom-wbar,
#custom-cliphist,
#custom-power,
#network,
#custom-notifications,
#pulseaudio,
#custom-spotify,
#taskbar,
#tray,
#custom-updates,
#window,
#workspaces,
#custom-l_end,
#custom-r_end,
#custom-sl_end,
#custom-sr_end,
#custom-rl_end,
#custom-rr_end {
    color: @main-fg;
    background: rgba(0, 0, 0, 0.01);
    opacity: 1;
    margin: 4px 0px 4px 0px;
    padding-left: 4px;
    padding-right: 4px;
}

#workspaces {
  padding: 0px;
  padding-left: 4px;
  padding-right: 2px;
}

#taskbar {
    padding: 0px;
    padding-right: 9px;
    padding-left: 9px;
    opacity: 0.90;
}

#idle_inhibitor{
    padding: 0px;
    color: @main-fg;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 6px;
    padding-left: 6px;
    opacity: 1;
}

#clock {
    padding: 0px;
    color: @main-fg;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 6px;
    padding-left: 6px;
    opacity: 1;
}

#custom-cpuinfo,
#memory {
    padding: 0px;
    color: #9ccfd8;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 6px;
    padding-left: 6px;
    opacity: 1;
}

#cpu {
    padding: 0px;
    color: #9ccfd8;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 6px;
    padding-left: 6px;
    opacity: 1;
}

#custom-gpuinfo {
    padding: 0px;
    color: #9ccfd8;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 6px;
    padding-left: 6px;
    opacity: 1;
}

#tray {
    padding: 0px;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 3px;
    padding-left: 3px;
    opacity: 0.90;
}

#custom-updates,
#pulseaudio {
    padding: 0px;
    color: #eb6f92;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 9px;
    padding-left: 9px;
    opacity: 1;
}

#network {
    padding: 0px;
    color: #eb6f92;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 9px;
    padding-left: 9px;
    opacity: 1;
}

#custom-keybindhint {
    padding: 0px;
    color: #eb6f92;
    background: rgba(0, 0, 0, 0.01);
    padding-right: 9px;
    padding-left: 9px;
    opacity: 1;
}

#mpris {
    color: #33C668;
    background: rgba(0, 0, 0, 0.01);
    opacity: 1;
    margin: 4px 0px 4px 0px;
    padding-left: 4px;
    padding-right: 4px;
}

#custom-r_end {
    border-radius: 0px 21px 21px 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-l_end {
    border-radius: 21px 0px 0px 21px;
    margin-left: 9px;
    padding-left: 3px;
}

#custom-sr_end {
    border-radius: 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-sl_end {
    border-radius: 0px;
    margin-left: 9px;
    padding-left: 3px;
}

#custom-rr_end {
    border-radius: 0px 7px 7px 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-rl_end {
    border-radius: 7px 0px 0px 7px;
    margin-left: 9px;
    padding-left: 3px;
}
